version: "3.3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 1935:1935

  gcsproxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    environment:
      - PORT=8081
      - GCS_BUCKET=gs://openmind-videostream-region
      - GOOGLE_APPLICATION_CREDENTIALS=/go/src/app/service-account.json
    ports:
      - 8081:8081
