apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-stream-server.fullname" . }}
  labels:
    {{- include "nginx-stream-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .Values.publishPassword) }}
  publish-password: {{ .Values.publishPassword | b64enc | quote }}
  {{- else }}
  publish-password: {{ required "A publish password is required!" .Values.publishPassword }}
  {{- end }}
